[package]
name = "opentype"
version = "0.0.8"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/opentype"
homepage = "https://github.com/stainless-steel/opentype"
description = "The package provides a parser for OpenType fonts."

[dependencies]
date = "0.1"

[dev-dependencies]
assert = "0.1"
