[package]
name = "opentype"
version = "0.3.2"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]
license = "MIT"
repository = "https://github.com/stainless-steel/opentype"
homepage = "https://github.com/stainless-steel/opentype"
documentation = "https://stainless-steel.github.io/opentype"
description = "The package provides a parser for OpenType fonts."

[[test]]
name = "opentype"
path = "tests/lib.rs"
